name: Quality Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM

jobs:
  quality-analysis:
    name: 📊 Quality Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run warnings analysis
      run: npm run analyze:warnings
      continue-on-error: true

    - name: Upload warnings report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: warnings-report
        path: warnings-report.md
        retention-days: 30


